// tailwind.config.js
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        outline: "#a78a87",
        "primary-fixed": "#ffdad6",
        "surface-container-highest": "#353534",
        "secondary-fixed-dim": "#e9c176",
        "surface-container-low": "#1c1b1b",
        "inverse-on-surface": "#313030",
        "tertiary-fixed": "#e4e2e1",
        "on-primary": "#690007",
        "secondary-container": "#604403",
        "primary-fixed-dim": "#ffb4ac",
        "on-primary-fixed": "#410003",
        "surface-bright": "#393939",
        "on-tertiary-fixed": "#1b1c1c",
        "primary-container": "#910e14",
        "on-primary-container": "#ff9b92",
        error: "#ffb4ab",
        "surface-dim": "#131313",
        "on-primary-fixed-variant": "#900d13",
        "tertiary-container": "#484747",
        "inverse-primary": "#b22a27",
        "on-tertiary": "#303030",
        "surface-container-lowest": "#0e0e0e",
        surface: "#131313",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed-variant": "#5d4201",
        "on-surface-variant": "#e0bfbc",
        "on-tertiary-container": "#b7b5b5",
        primary: "#ffb4ac",
        "surface-tint": "#ffb4ac",
        "on-secondary-fixed": "#261900",
        background: "#131313",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-secondary": "#412d00",
        tertiary: "#c8c6c5",
        "on-secondary-container": "#dab36a",
        "surface-container": "#201f1f",
        "inverse-surface": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-variant": "#353534",
        secondary: "#e9c176",
        "outline-variant": "#58413f",
        "on-tertiary-fixed-variant": "#474746",
        "on-background": "#e5e2e1",
        "secondary-fixed": "#ffdea5",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};